@startuml
!includeurl https://raw.githubusercontent.com/hillairet/C4Seq-Plantuml/main/c4seq.puml
!include <logos/python>
!include <logos/mongodb>
!include <logos/redis>
!include <logos/nodejs>
!include <logos/mysql>
!include <logos/memcached>

!include c4seq.puml

title Order and discount processing

Person("dude", "Dude")
Container("container", "App", $sprite=python)
ContainerDb("containerdb", "Database", "mongodb", "Database description", $sprite=mongodb) 
ContainerQueue("containerqueue", "Queue", "redis", "A useful queue", $sprite=redis)
Container_Ext("container_ext", "External service", $sprite=nodejs)
ContainerDb_Ext("containerdb_ext", "External DB", $sprite=mysql)
ContainerQueue_Ext("containerqueue_ext", "External queue", $sprite=memcached)

Rel(dude, container, "Do things")
activate dude
activate container

Rel(container, containerdb, "Read things")
Rel(container, container, "Process internally")
Rel(container, containerqueue, "Push item")
Rel(container, container_ext, "Call API")
Rel(container, containerdb_ext, "Read other things")
Rel(container, containerqueue_ext, "Push another item")

Rel_Dash(container, dude, "Done")

deactivate container
deactivate dude

@enduml
